include:
  - local: 'v1/common/templates.yml'

Semver:
  extends: .semver_template
  script:
    - dotnet /app/gitlab-semver-helper.dll -accessToken $SCRT_GITLAB_API_PRIVATE_TOKEN -modPipelineRevision "True"
    - cat ./version.txt

Build_Nuget:
  stage: Build
  script:
    - job: Semver
    - VERSION=$(cat ./version.txt).Substring(1)
    - dotnet build
  allow_failure: false
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /.*hotfix.*/ || $CI_COMMIT_BRANCH =~ /.*release.*/ || $CI_MERGE_REQUEST_ID
      when: on_success
  tags:
    - dotnet

Publish[Nexus]:
  stage: Publish
  needs:
    - job: Semver
    - job: Build_Nuget
  script:
    - $VERSION = Get-Content .\version.txt -Raw
    - $VERSION = $VERSION.Substring(1)
    - dotnet build -p:Version=$VERSION -c Release -o ./output/ $SOLUTION_NAME.sln
    - nuget push ./output/$PROJ_NUGET_PACKAGE_NAME.$VERSION.nupkg -Source Nexus
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /.*hotfix.*/ || $CI_COMMIT_BRANCH =~ /.*feature.*/
      when: manual
  tags:
    - dotnet
