# Simple test workflow to debug main pipeline issues
name: Test Workflow

on:
  push:
    branches:
      - gh-gl-mig
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - gh-gl-mig
      - main
      - develop
  workflow_dispatch:

jobs:
  test-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List repository contents
        run: |
          echo "=== Repository Root Contents ==="
          ls -la
          echo ""
          echo "=== All .csproj files ==="
          find . -name "*.csproj" -type f
          echo ""
          echo "=== All .sln files ==="
          find . -name "*.sln" -type f
          echo ""
          echo "=== Check for Dockerfile ==="
          [ -f "Dockerfile" ] && echo "Dockerfile found" || echo "No Dockerfile"
          echo ""
          echo "=== Check for NuGet files ==="
          find . -name "*.nupkg" -o -name "*.nuspec" -type f
          echo ""
          echo "=== Search for AspNetCore ==="
          grep -r "Microsoft.AspNetCore" . --include="*.csproj" || echo "No AspNetCore found"
          echo ""
          echo "=== Search for Extensions.Hosting ==="
          grep -r "Microsoft.Extensions.Hosting" . --include="*.csproj" || echo "No Extensions.Hosting found"

  test-simple-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Simple build test
        run: |
          echo "Testing simple build process..."
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "This job always runs to test the workflow execution"
